### ISSUE TITLE
nil as NSDictionary's key

### ISSUE THREAD

**Issue by rafalkitta** [sensorberg-dev/ios-sdk#20]
### Classification (type of problem: security, crash, performance, serious bug, feature, enhancement etc)
Crash

### Reproducibility (always, sometimes, rarely, N.A.)
N.A
Didn't try to reproduce crash under debugger.

### Description
Fatal Exception: NSInvalidArgumentException
*** -[__NSDictionaryM removeObjectForKey:]: key cannot be nil

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x181aad1b8 __exceptionPreprocess
1  libobjc.A.dylib                0x1804e455c objc_exception_throw
2  CoreFoundation                 0x1819aa7a4 -[__NSDictionaryM removeObjectForKey:]
3  SensorbergSDK                  0x101731828 (Missing)
4  tolo                           0x1019d54d8 (Missing)
5  SensorbergSDK                  0x1017302bc (Missing)
6  SensorbergSDK                  0x10172efd4 (Missing)
7  CoreLocation                   0x189ab1f90 (null)
8  CoreLocation                   0x189aa34b8 (null)
9  CoreFoundation                 0x181a5aa44 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
10 CoreFoundation                 0x181a5a240 __CFRunLoopDoBlocks
11 CoreFoundation                 0x181a58538 __CFRunLoopRun
12 CoreFoundation                 0x1819862b8 CFRunLoopRunSpecific
13 GraphicsServices               0x18343a198 GSEventRunModal
14 UIKit                          0x1879cd7fc -[UIApplication _run]
15 UIKit                          0x1879c8534 UIApplicationMain
16 App                          0x1002800b4 main (AppDelegate.swift:24)
17 libdispatch.dylib              0x1809695b8 (Missing)

### Sensorberg SDK version
2.5.3

### iOS version
8, 9, 10

### Device
iPhone, iPad

### Additional notes

**Comment by SanggeonPark** [comment]
Hi rafalkitta,
I'm investigating on it.
Can you please try to run the app under debugger?

**Comment by rafalkitta** [comment]
Hi,
I have it under debugger, crash didn't occur for me. I only see it in Crashlytics.

**Comment by tagyro** [comment]
@rafalkitta Thank you for reporting this issue - we fixed it and released [v2.5.4](https://github.com/sensorberg-dev/ios-sdk/releases/tag/2.5.4)
