### ISSUE TITLE
Cocoapod: ‘objc_geohash/GeoHash.h’ file not found

### ISSUE THREAD

**Issue by brainray** [sensorberg-dev/ios-sdk#21]
Hi there, after installing v2.5.x with Cocoapods and disabling 'use_frameworks!' in the Podfile, Xcode gives me the above error. 
The reason for this, is that the symlink-folder for the geohash framework in the /Pods/Headers/Public/ folder is named '**objc-geohash**' and not '**objc_geohash**' (the underscore;-) as named in the e.g. SBLocation.m where it's referenced.
After renaming by hand everything is fine.

**Comment by tagyro** [comment]
This is a known issue; please update to v2.5.5 and `use_frameworks!` in the pod file.
In a future version we will phase out `objc-geohash` and the issue will be fixed.
Thanks for the report, @brainray
