### ISSUE TITLE
AFNetworking 2.x required for v1.0.4?

### ISSUE THREAD

**Issue by wberger** [sensorberg-dev/ios-sdk#5]
Hi,

We have problems with Sensorberg SDK 1.0.2 not sending notifications to our app.

Thus we tried to upgrade Sensorberg from 1.0.2 to 1.0.4. However, this (bugfix?) release introduces breaking changes by requiring AFNetworking 2.x. Our whole app builds on AFNetworking 1.x, so this would require a complete rewrite of our networking libraries, which is not an option at the moment.

Could you please get rid of this dependency or at least provide a version which uses AFNetworking 1.x instead?

**Comment by falkorichter** [comment]
Hello there, 
we will not provide a version which uses the insecure AFNetworking 1.x. You should stay on your version  (1.0.2) of the SDK in the mean while. AFNetworking 1.x is about 2 years old now without Security fixes, including the SSL problems of last year.

What is the problem that made you want to switch to 1.0.4? We should address that issue. Please open an issue explaining the problems you are having so we can help you solve them.

Schöne Grüße aus Berlin

Falko

**Comment by wberger** [comment]
I will forward this information.

However, as far as I remember, only AFNetworking 2.x was affected by the SSL issue, while AFNetworking 1.x was not due to a different implementation.

**Comment by tagyro** [comment]
Please use [v1.0.2](https://github.com/sensorberg-dev/ios-sdk/releases/tag/1.0.2) which is still a binary.
*ps. Internally, SBSDK always used the latest version of AFNetworking - we just hid that with a namespace to avoid collisions.*
